version: "3"
services:
  # Development
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/frontend/src
    environment:
      - NODE_ENV=development
      - DISABLE_ESLINT_PLUGIN=true
    depends_on:
      - backend-dev
    links:
      - backend-dev
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./backend/src:/app/backend/src
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=postgresql://postgres:password@database-dev:5432/ptdb
    depends_on:
      - database-dev
    links:
      - database-dev
  database-dev:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ptdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  db:
