version: "3"
services:
  # Development
  front-end-dev:
    container_name: front-end-dev
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./front-end/src:/app/front-end/src
    environment:
      - NODE_ENV=development
      - DISABLE_ESLINT_PLUGIN=true
  back-end-dev:
    container_name: back-end-dev
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./back-end/src:/app/back-end/src
    env_file:
      - ./back-end/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - database-dev
  database-dev:
    container_name: database-dev
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ptdb
volumes:
  db:
networks:
  bridge:
