version: "3"
services:
  # Development
  front-end-dev:
    build:
      context: ./front-end
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./front-end/src:/app/front-end/src
    environment:
      - NODE_ENV=development
      - DISABLE_ESLINT_PLUGIN=true
    depends_on:
      - back-end-dev
    links:
      - back-end-dev
  back-end-dev:
    build:
      context: ./back-end
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./back-end/src:/app/back-end/src
    env_file:
      - ./back-end/.env
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING=postgresql://postgres:password@database-dev:5432/ptdb
    depends_on:
      - database-dev
    links:
      - database-dev
  database-dev:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ptdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  db:
