import React from "react";

function TermsOfService(): React.ReactElement {
    return (
        <div className="settings-subpage-container">
            <h2 className="settings-subpage-header">Terms of Service</h2>
            <div className="settings-tos-content">
                <div className="settings-tos-paragraph">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Volutpat odio facilisis mauris sit amet. Tortor dignissim convallis aenean et tortor at. Dapibus ultrices in iaculis nunc sed augue. Vel fringilla est ullamcorper eget nulla facilisi etiam. Morbi tristique senectus et netus et malesuada. Sed nisi lacus sed viverra tellus in. Velit dignissim sodales ut eu sem. Sem fringilla ut morbi tincidunt augue interdum velit. Sed risus ultricies tristique nulla aliquet enim tortor at. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Dignissim convallis aenean et tortor at risus viverra. Non arcu risus quis varius. Non nisi est sit amet facilisis magna etiam tempor orci.
                </div>
                <div className="settings-tos-paragraph">
                    Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. A lacus vestibulum sed arcu non. Diam maecenas ultricies mi eget mauris. Congue eu consequat ac felis. Egestas congue quisque egestas diam in arcu cursus. Ipsum nunc aliquet bibendum enim facilisis gravida neque. Quis viverra nibh cras pulvinar mattis nunc. Dictumst quisque sagittis purus sit. Pellentesque pulvinar pellentesque habitant morbi tristique senectus. Erat velit scelerisque in dictum. Nisl nunc mi ipsum faucibus vitae aliquet nec. Habitant morbi tristique senectus et netus et malesuada fames. Libero nunc consequat interdum varius sit amet mattis. Diam quam nulla porttitor massa id neque aliquam vestibulum morbi. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Eget mauris pharetra et ultrices neque ornare aenean. Facilisi etiam dignissim diam quis enim lobortis. Enim eu turpis egestas pretium aenean pharetra.
                </div>
                <div className="settings-tos-paragraph">
                    At tempor commodo ullamcorper a lacus vestibulum sed. Elit sed vulputate mi sit. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Et ultrices neque ornare aenean euismod elementum nisi. At tempor commodo ullamcorper a. Pharetra et ultrices neque ornare aenean euismod. A scelerisque purus semper eget. Cursus vitae congue mauris rhoncus aenean vel. Donec ac odio tempor orci dapibus ultrices in iaculis. Mauris cursus mattis molestie a iaculis at erat pellentesque adipiscing. Tristique senectus et netus et malesuada fames ac.
                </div>
                <div className="settings-tos-paragraph">
                    Ut ornare lectus sit amet est. Nisl purus in mollis nunc. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Dignissim suspendisse in est ante in nibh. Integer malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Amet justo donec enim diam. Bibendum arcu vitae elementum curabitur vitae nunc. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Sed libero enim sed faucibus turpis in eu. Bibendum est ultricies integer quis auctor elit sed vulputate. In cursus turpis massa tincidunt dui ut ornare. Eu mi bibendum neque egestas congue quisque egestas.
                </div>
                <div className="settings-tos-paragraph">
                    Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Sit amet mattis vulputate enim. Ut ornare lectus sit amet est placerat in egestas. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Neque volutpat ac tincidunt vitae. Facilisis leo vel fringilla est. Orci sagittis eu volutpat odio facilisis. Vitae et leo duis ut diam quam. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Eleifend mi in nulla posuere sollicitudin. Libero volutpat sed cras ornare. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Elit at imperdiet dui accumsan.
                </div>
                <div className="settings-tos-paragraph">
                    Eget nulla facilisi etiam dignissim diam quis enim lobortis. Et ligula ullamcorper malesuada proin libero nunc. Faucibus vitae aliquet nec ullamcorper sit. Donec adipiscing tristique risus nec feugiat in fermentum posuere urna. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Amet purus gravida quis blandit. Arcu odio ut sem nulla pharetra. Eu non diam phasellus vestibulum lorem sed risus. Sollicitudin nibh sit amet commodo. Mattis rhoncus urna neque viverra justo nec ultrices. Etiam sit amet nisl purus. Interdum posuere lorem ipsum dolor sit amet. Eget nulla facilisi etiam dignissim diam. At volutpat diam ut venenatis tellus in metus. Imperdiet dui accumsan sit amet nulla. Adipiscing tristique risus nec feugiat in fermentum posuere. Neque vitae tempus quam pellentesque nec nam aliquam. Sed euismod nisi porta lorem mollis aliquam ut porttitor. Pulvinar mattis nunc sed blandit. Felis eget velit aliquet sagittis id consectetur purus ut faucibus.
                </div>
                <div className="settings-tos-paragraph">
                    Metus aliquam eleifend mi in. A cras semper auctor neque vitae tempus quam. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Neque viverra justo nec ultrices dui sapien. Nullam ac tortor vitae purus faucibus ornare suspendisse. Consequat semper viverra nam libero justo laoreet sit. Felis imperdiet proin fermentum leo vel orci porta non. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Dictum fusce ut placerat orci nulla pellentesque. Ultrices dui sapien eget mi proin. Sit amet mattis vulputate enim nulla aliquet porttitor lacus luctus. Id diam maecenas ultricies mi eget mauris. Bibendum neque egestas congue quisque egestas.
                </div>
                <div className="settings-tos-paragraph">
                    Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Orci ac auctor augue mauris augue neque gravida in. A arcu cursus vitae congue mauris rhoncus. Pulvinar sapien et ligula ullamcorper. Urna nunc id cursus metus aliquam eleifend mi in nulla. Venenatis urna cursus eget nunc scelerisque viverra. Aenean et tortor at risus viverra adipiscing at. Dictum sit amet justo donec enim diam vulputate ut. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Purus non enim praesent elementum facilisis leo vel fringilla. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Feugiat nisl pretium fusce id velit ut tortor pretium. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Arcu bibendum at varius vel pharetra vel turpis nunc. Elit sed vulputate mi sit amet mauris commodo. Facilisi morbi tempus iaculis urna id. Phasellus egestas tellus rutrum tellus pellentesque eu. Sagittis eu volutpat odio facilisis mauris. Viverra vitae congue eu consequat ac felis.
                </div>
                <div className="settings-tos-paragraph">
                    Placerat duis ultricies lacus sed turpis tincidunt. Odio ut sem nulla pharetra diam sit amet. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Lectus sit amet est placerat. Imperdiet proin fermentum leo vel orci. Nisl pretium fusce id velit ut tortor pretium. Id neque aliquam vestibulum morbi blandit. Turpis tincidunt id aliquet risus feugiat in. Faucibus purus in massa tempor nec feugiat. Consequat ac felis donec et odio pellentesque diam volutpat commodo. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque.
                </div>
                <div className="settings-tos-paragraph">
                    Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Tortor consequat id porta nibh venenatis cras sed. Sit amet consectetur adipiscing elit pellentesque. Adipiscing tristique risus nec feugiat in. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque. Netus et malesuada fames ac. Cras tincidunt lobortis feugiat vivamus at augue. Egestas sed tempus urna et pharetra. Ultrices sagittis orci a scelerisque. Consectetur a erat nam at lectus urna duis convallis convallis.
                </div>
            </div>
        </div>
    );
}

export default TermsOfService;
